version: '3'
services:
  rail6:
    build:
      context: .
      dockerfile: ./Dockerfile.rail6
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/app
