FROM ruby:2.7

# Register Yarn package source.
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Install packages.
RUN apt update -qq
RUN apt install -y postgresql-client nodejs yarn

WORKDIR /home/app

RUN gem install bundler
RUN gem install webpacker
RUN gem install rails

ENTRYPOINT [ "/bin/bash" ]